language: node_js
node_js:
  - "10"
cache: npm

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

branches:
  only:
    - master
env:
  global:
    - REF=github.com/ruesin/php-tree.git
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: ${TOKEN}
#   local-dir: ./_book/
#   target-branch: gh-pages
#   #verbose: true
#   keep-history: true
#   on:
#     branch: master

after_script:
  - cd _book
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages
# after_script:
#   - git add _book
#   - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
#   # - git subtree push --prefix=_book origin gh-pages
#   - git subtree push --prefix=_book https://${TOKEN}@${REF} gh-pages